ThAmCo.Events/Controllers/EventGuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;

namespace ThAmCo.Events.Controllers
{
    public class EventGuestController : Controller
    {
        private readonly EventsContext _context;

        public EventGuestController(EventsContext context)
        {
            _context = context;
        }

        // GET: EventGuest/Index/1
        public async Task<IActionResult> Index(int? id = null)
        {
            var eventsContext = _context.EventGuest.AsQueryable();      // turns DBset into searchable list type

            if (id != null)
            {
                eventsContext = eventsContext.Where( g => g.EventId == id);
            }

            eventsContext = eventsContext.Include(g => g.Guest)
                .Include(e => e.Event);

            return View(await eventsContext.ToListAsync());
        }

        // GET: EventGuest/Create
        public IActionResult Create()
        {
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name");       // Creates a Select list to view events and guests
            ViewData["GuestId"] = new SelectList(_context.Guest, "GuestId", "FirstName");
            return View();
        }

        // POST: EventGuest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,GuestId")] EventGuest eventGuest)        // [Bind] attribute is used to include only specific properties during model binding
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventGuest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "EventId", "Name", eventGuest.EventId);
            ViewData["GuestId"] = new SelectList(_context.Guest, "GuestId", "FirstName", eventGuest.GuestId);
            return View(eventGuest);
        }

        // GET: EventGuest/Delete?eventId=2&guestId=1
        public async Task<IActionResult> Delete(int? eventId, int? guestId)
        {
            if (eventId == null || guestId == null || _context.EventGuest == null)
            {
                return NotFound();
            }

            var eventGuest = await _context.EventGuest
                .Include(e => e.Guest)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == eventId && m.GuestId == guestId);
            if (eventGuest == null)
            {
                return NotFound();
            }

            return View(eventGuest);
        }

        // POST: EventGuest/Delete?eventId=2&guestId=1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? eventId, int? guestId)
        {
            if (_context.EventGuest == null)
            {
                return Problem("Entity set 'EventsContext.EventGuest'  is null.");
            }
            var eventGuest = await _context.EventGuest.FindAsync(eventId, guestId);
            if (eventGuest != null)
            {
                _context.EventGuest.Remove(eventGuest);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: EventGuest/Edit?eventId=1&guestId=1
        public async Task<IActionResult> Edit(int? eventId, int? guestId)
        {
            if (eventId == null || guestId == null || _context.EventGuest == null)
            {
                return NotFound();
            }

            var eventGuest = await _context.EventGuest
                .Include(e => e.Guest)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == eventId && m.GuestId == guestId);

            if (eventGuest == null)
            {
                return NotFound();
            }

            return View(eventGuest);
        }

        // POST: EventGuest/Edit?eventId=1&guestId=1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int eventId, int guestId, [Bind("EventId,GuestId,HasAttended")] EventGuest eventGuest)
        {
            if (eventId != eventGuest.EventId || guestId != eventGuest.GuestId)
            {
                return NotFound();
            }

            var existingEventGuest = await _context.EventGuest      // Retrieve the existing EventGuest entity from the database
                .Include(e => e.Guest)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.EventId == eventId && m.GuestId == guestId);

            if (existingEventGuest == null)
            {
                return NotFound();
            }

            existingEventGuest.HasAttended = eventGuest.HasAttended;        // Update only the HasAttended property

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(existingEventGuest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventGuestExists(existingEventGuest.EventId, existingEventGuest.GuestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(existingEventGuest);
        }

        private bool EventGuestExists(int eventId, int guestId)
        {
            return _context.EventGuest.Any(e => e.EventId == eventId && e.GuestId == guestId);
        }

    }
}

ThAmCo.Events/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;

namespace ThAmCo.Events.Controllers
{
    public class StaffController : Controller
    {
        private readonly EventsContext _context;

        public StaffController(EventsContext context)
        {
            _context = context;
        }

        // GET: Staff
        public async Task<IActionResult> Index()
        {
            var staffwithevent = await _context.Staff.Include(s => s.Events).ToListAsync();      // display a list of guests with context on events
            return View(staffwithevent);
        }

        // GET: Staff/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @staff = await _context.Staff
                .Include(s => s.Events)
                .FirstOrDefaultAsync(s => s.StaffId == id);

            if (@staff == null)
            {
                return NotFound();
            }
            return View(@staff);
        }

        // GET: Staff/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffId,LastName,FirstName")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // GET: Staff/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Staff == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        // POST: Staff/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffId,LastName,FirstName")] Staff staff)
        {
            if (id != staff.StaffId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.StaffId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        private bool StaffExists(int id)
        {
          return _context.Staff.Any(e => e.StaffId == id);
        }
    }
}

ThAmCo.Events/Views/Staff/Create.cshtml
@model ThAmCo.Events.Data.Staff

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Staff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Staff/Details.cshtml
@model ThAmCo.Events.Data.Staff

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Staff</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.StaffId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ThAmCo.Events/Views/Staff/Edit.cshtml
@model ThAmCo.Events.Data.Staff

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Staff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StaffId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Staff/Index.cshtml
@model IEnumerable<ThAmCo.Events.Data.Staff>

@{
    ViewData["Title"] = "Index";
}

<h1>Staff List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("First name")
            </th>
            <th>
                @Html.DisplayName("Last name")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StaffId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StaffId">Details</a> |
                <a asp-controller="EventGuest" asp-action="StaffIndex" 
                   asp-route-id="@item.StaffId">Event List</a>
            </td>
        </tr>
}
    </tbody>
</table>